# -*- coding: utf-8 -*-
"""DAA_Assignment5_Code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k-B51aTZ5tO3vqJzZ70r9bD4jITKn4iO
"""

import random
def quicksort(arr, start , stop):
    if(start < stop):
          
        pivotindex = partitionrand(arr,\
                             start, stop)
          
        quicksort(arr , start , pivotindex-1)
        quicksort(arr, pivotindex + 1, stop)
  
# This function generates random pivot,
def partitionrand(arr , start, stop):
  
    # Generating a random number 
    randpivot = random.randrange(start, stop)
  
    # Swapping the starting element of the array and the pivot
    arr[start], arr[randpivot] = \
        arr[randpivot], arr[start]
    return partition(arr, start, stop)
  
def partition(arr,start,stop):
    pivot = start # pivot
      
    # a variable to memorize where the 
    i = start + 1 
      
    # partition in the array starts from.
    for j in range(start + 1, stop + 1):
          
        # if the current element is smaller or equal to pivot, shift it to the left side of the partition.
        if arr[j] <= arr[pivot]:
            arr[i] , arr[j] = arr[j] , arr[i]
            i = i + 1
    arr[pivot] , arr[i - 1] =\
            arr[i - 1] , arr[pivot]
    pivot = i - 1
    return (pivot)
def partition2(array, low, high):
 
    # choose the rightmost element as pivot
    pivot = array[high]
 
    # pointer for greater element
    i = low - 1
 
    # traverse through all elements
    # compare each element with pivot
    for j in range(low, high):
        if array[j] <= pivot:
 
            # If element smaller than pivot is found
            # swap it with the greater element pointed by i
            i = i + 1
 
            # Swapping element at i with element at j
            (array[i], array[j]) = (array[j], array[i])
 
    # Swap the pivot element with the greater element specified by i
    (array[i + 1], array[high]) = (array[high], array[i + 1])
 
    # Return the position from where partition is done
    return i + 1
 
# function to perform quicksort
 
 
def quickSort2(array, low, high):
    if low < high:
 
        # Find pivot element such that
        # element smaller than pivot are on the left
        # element greater than pivot are on the right
        pi = partition(array, low, high)
 
        # Recursive call on the left of pivot
        quickSort2(array, low, pi - 1)
 
        # Recursive call on the right of pivot
        quickSort2(array, pi + 1, high)

ch = "1"
while(ch!="0"):
  print("1. Deterministic")
  print("2. Randomized")
  ch = input("0. Exit")
  if(ch=="0"):
    break
  elif ch=="1":
    num = int(input("Enter number of elements : "))
    arr = []
    for i in range(0,num):
      temp = int(input("Enter element : "))
      arr.append(temp)
    quickSort2(arr, 0, len(arr) - 1)
    print("Sorted array : ",arr)
  elif ch=="2":
    num = int(input("Enter number of elements : "))
    arr = []
    for i in range(0,num):
      temp = int(input("Enter element : "))
      arr.append(temp)
    quicksort(arr, 0, len(arr) - 1)
    print("Sorted array : ",arr)



